config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users, only: :show do
    resources :decks, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "users/:id/courses", to: "users#courses", as: :user_courses
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  resources :courses do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, except:[:new, :create]
  resources :posts
  resources :decks, only: [:show] do
    resources :cards, only: [:new, :create]
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck

end

app/models/course.rb
class Course < ApplicationRecord
  has_many :bookings
  # dependent: :destroy add later
  has_one_attached :photo
  has_one_attached :free_material
  has_one_attached :paid_material
  has_rich_text :description
  monetize :price_cents

  COURSE_TYPE = ['Online Test', 'Interview', 'Other']
  validates :name, :course_type, :paid_material, :description, :example_question, presence: true
  validates :course_type, inclusion: { in: COURSE_TYPE }
end

app/models/course_type.rb
class CourseType < ApplicationRecord
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course
  monetize :amount_cents
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :rich_content
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  has_many :orders, dependent: :destroy
  has_many :bookings
  has_many :courses, through: :bookings
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show]
  before_action :find_course, only: [:create]
  before_action :find_user, only: [:create, :index]

  def index
    @my_bookings = current_user.bookings.where.order(deadline: :desc)
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.course = @course
    if @booking.save!
      redirect_to bookings_path
    else
      render '/courses/show'
    end
  end

  private

  def find_user
    @user = current_user
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def find_course
    @course = Course.find(params[:course_id])
  end

  def booking_params
    params.require(:booking)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @deck = Deck.find(params[:deck_id])
    @card = Card.new
    authorize @deck
  end

  def create
    @card = Card.new(card_params)
    @deck = Deck.find(params[:deck_id])
    @card.deck = @deck
    authorize @deck
    if @card.save
      redirect_to deck_path(@deck)
    else
      render :new
    end
  end

  private

  def card_params
    params.require(:card).permit(:front_side, :back_side)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = policy_scope(Course)
  end

  def show
    @booking = Booking.new
  end

  #use pundit to only allow admin to do these methods
  def new
    @course = Course.new
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course

    if @course.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @course.update(course_params)
    redirect_to course_path(@course)
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private

  def set_course
    @course = Course.find(params[:id])
    authorize @course
  end

  def course_params
    params.require(:course).permit(:name, :course_type, :paid_material, :description, :example_question, :photo, :free_material, :paid_material, :price_cents)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!, :set_deck, only: [:show]

  def show
    @card = Card.new
    @cards = Card.all
  end

  def new
    @user = current_user
    @deck = Deck.new
    authorize @deck
  end

  def create
    @deck = Deck.new(deck_params)
    @user = current_user
    @deck.user = @user
    authorize @deck

    if @deck.save
      redirect_to deck_path(@deck)
    else
      render :new
    end
  end

  private

  def set_deck
    @deck = Deck.find(params[:id])
    authorize @deck
  end

  def deck_params
    params.require(:deck).permit(:title, :category)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
  course = Course.find(params[:course_id])
  order  = Order.create!(course: course, amount: course.price, state: 'pending', user: current_user)
  authorize order
  session = Stripe::Checkout::Session.create(
    payment_method_types: ['card'],
    line_items: [{
      name: course.name,
      images: [course.photo],
      amount: course.price_cents,
      currency: 'gbp',
      quantity: 1
    }],
    success_url: order_url(order),
    cancel_url: order_url(order)
  )
  order.update(checkout_session_id: session.id)
  redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
    authorize @order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    authorize @order
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @posts = policy_scope(Post).order(created_at: :desc)
  end

  def new
    @post = Post.new
    authorise @post
  end


  def create
    @post = Post.new(post_params)
    authorise @post

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :content, :summary, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
    # @decks = Deck.all
    # authorize @decks
    # @bookings = @user.bookings
    # @orders = @user.orders
  end

  private

  def user_params
    params.require(:user).permit(:email, :encrypted_password, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cards/new.html.erb
<div class="container my-3">
  <h3>Add a card</h3>
</div>

<div class="container">
  <%= simple_form_for [@deck, @card] do |f| %>

    <div class="form-inputs">
      <%= f.input :front_side,
                  required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :back_side,
                  required: true %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-ghost" %>
    </div>

  <% end %>
</div>

app/views/courses/edit.html.erb
<div class="container my-3">
  <h3>Edit <%= @course.name %></h3>
</div>

<div class="container">
  <%= simple_form_for(@course) do |f| %>

    <div class="form-inputs">
      <%= f.input :name,
                  required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :course_type,
                required: true,
                collection: ['Online Test', 'Interview', 'Other'] %>
    </div>

    <div class="form-inputs">
      <%= f.input :paid_material,
                required: true,
                input_html: { class: "toggle" } %>
    </div>

    <div class="form-inputs">
      <%= f.label :description,
                      label: "Course description" %>
      <%= f.rich_text_area :description,
                            required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :example_question %>
    </div>

    <div class="form-inputs">
      <%= f.input :photo,
                label: "Course photo",
                as: :file %>
    </div>

     <div class="form-inputs">
      <%= f.input :files,
                label: "Course Files",
                as: :file %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-ghost" %>
    </div>

  <% end %>
</div>

app/views/courses/index.html.erb
<div class="container">
  <div class="cards-container">
    <div class="cards">

      <% @courses.each do |course| %>
        <% if course.photo.attached? %>
          <%= link_to course_path(course), class: 'card-text' do  %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path course.photo.key %>')">
              <%= course.name %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <%if policy(@courses).new? %>
    <%= link_to "Add a course", new_course_path(@course), class: "btn btn-dark" %>
  <% else %>
    <%= "Not allowed to add course" %>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="container my-3">
  <h3>Add a new course</h3>
</div>

<div class="container">
  <%= simple_form_for @course do |f| %>

    <div class="form-inputs">
      <%= f.input :name,
                  required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :course_type,
                required: true,
                collection: ['Online Test', 'Interview', 'Other'] %>
    </div>

    <div class="form-inputs">
      <%= f.label :description,
                      label: "Course description" %>
      <%= f.rich_text_area :description,
                            required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :example_question %>
    </div>

    <div class="form-inputs">
      <%= f.input :photo,
                label: "Course photo",
                as: :file %>
    </div>

    <div class="form-inputs">
      <%= f.input :free_material,
                label: "Free Material File",
                as: :file %>
    </div>

    <div class="form-inputs">
      <%= f.input :paid_material,
                label: "Paid Material File",
                as: :file %>
    </div>

    <div class="form-inputs">
      <%= f.input :price_cents,
                label: "Paid Material Price",
                as: :integer %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-ghost" %>
    </div>

  <% end %>
</div>

app/views/courses/show.html.erb
 <div class="mx-5 my-3 py-3 px-5">
  <%= link_to "Back to courses", courses_path, class: "btn btn-dark mb-3" %>
  <div class="d-flex justify-content-sm-between">
    <div class="d-flex flex-row">
      <div class="">
        <%= cl_image_tag @course.photo.key, class: "course-img" %>
      </div>
      <div class="col-sm-6">
        <h3 class="course-type-header"> <%= @course.course_type %></h3>
        <h1 class="course-header"> <%= @course.name %> </h1>
      </div>
    </div>
    <div class="col-sm-2 course-buy-buttons pt-5">
      <%=link_to "Free Material",rails_blob_path(@course.free_material, disposition: 'attachment'), class: "btn btn-flat btn-block my-3", target: 'blank'  %>
      <%=link_to "Paid Material",rails_blob_path(@course.paid_material, disposition: 'attachment'), class: "btn btn-flat btn-block mb-3", target: 'blank'  %>
      <p>Amount: <%= humanized_money_with_symbol(@course.price) %></p>
      <%= form_tag orders_path do %>
      <%= hidden_field_tag 'course_id', @course.id %>
      <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
      <% end %>
  <!--     <a class="btn btn-flat btn-block my-3" href="#">Free download</a>
      <a class="btn btn-flat btn-block mb-3" href="#"> Buy </a>
      <a class="btn btn-flat btn-block mb-3" href="#"> Consulting multi-pack</a> -->
    </div>
  </div>
  <div class="pt-3">
    <%= @course.description %> </p>
  </div>
  <% if policy(@course).edit? %>
    <%= link_to "Edit course", edit_course_path(@course), class: "btn btn-dark" %>
  <% end %>
  <% if policy(@course).destroy? %>
    <%= link_to "Delete course", course_path(@course), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete #{@course.name}?" }  %>
  <% end %>
</div>

app/views/decks/new.html.erb
<div class="container my-3">
  <h3>Add a new deck</h3>
</div>

<div class="container">
  <%= simple_form_for [@user, @deck] do |f| %>

    <div class="form-inputs">
      <%= f.input :title,
                  required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :category,
                required: true,
                collection: ['Online Test', 'Interview', 'Other'] %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-ghost" %>
    </div>

  <% end %>
</div>

app/views/decks/show.html.erb
<h1> <%= @deck.title %> flashcards </h1>
<!-- Create a container for cards -->
<div class="container mt-4 border-bottom border-warning border-10 d-flex justify-content-start">
  <button class="btn btn-bookings flip" data-target="upcoming-bookings">Upcoming</button>
</div>
<div class="container">
  <div class="container active">
    <% @cards.each do |card| %>
      <%= card.front_side %>
    <% end %>
  </div>
  <div class="container">
    <% @cards.each do |card| %>
      <%= card.back_side %>
    <% end %>
  </div>
</div>
<!-- Show the front-side of card  - backside hidden until flipped -->
<!-- add a flip button -->



<%= link_to "Add a new card",  new_deck_card_path(@deck), class: "btn btn-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradInterviewPrep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container">
        <%= render 'shared/navbar' %>
      </div>
      <div class="content-container">
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
      <div class="footer-container">
        <%= render "shared/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.course.photo, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
        <li><strong>COURSE</strong> <%= @order.course.name %></li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.course.photo, width: '100%' %></div>
    <div class="col">
      <h1>Checkout summary</h1>
      <p>Purchase of <strong><%= @order.course.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
      <button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% @posts.each do |post| %>
  <% if policy(post).edit? %>
    <%= link_to "Update post", edit_post_path(post) %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<div class="posts-index">
  <%= @posts.order(created_at: :desc).each do |post| %>
    <div class="post-card">
      <%= cl_image_tag post.photo.key, height: 300, width: 400, crop: :fill %>
      <div class="post-head">
        <h3><%= post.title %></h3>
      </div>
      <div class="post-summary">
        <p><%= post.summary %></p>
      </div>
    </div>
  <% end %>
</div>
<div class="">
  <% if policy(@posts).create? %>
    <%= link_to "New post", new_post_path(@post) %>
  <% end %>
</div>
<div class="container">
  <% if policy(@posts).create? %>
    <%= link_to "Add a post", new_post_path(@post), class: "btn btn-dark" %>
  <% end %>
</div>

app/views/posts/new.html.erb
<!-- <% if policy(Post).create? %>
  <%= link_to "New post", new_post_path %>
<% end %>
 -->

 <div class="container">
  <h3>Add a new post</h3>
 </div>

 <div class="container">
  <%= simple_form_for @post do |f| %>
    <div class="form-inputs">
      <%= f.input :title, required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :summary, required: true %>
    </div>

    <div class="form-inputs">
      <%= f.label :content, label: "Post content" %>
      <%= f.rich_text_area :content, required: true %>
    </div>

    <div class="form-inputs">
      <%= f.input :photo, label: "Post photo", as: :file %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-ghost" %>
    </div>

  <% end %>

 </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-socials">
    <a href="https://www.facebook.com/gradinterviewprep/" target="_blank"><i class="fab fa-facebook fa-lg"></i></a>
    <a href="https://www.youtube.com/channel/UCOu9kmrkWJtxPncCbDXD0YQ" target="_blank"><i class="fab fa-youtube fa-lg"></i></i></a>
  </div>
  <div class="footer-copyright">
    <span>  &copy;2021 Grad Interview Prep</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/abhaila/-grad_interview_prep/bba998048be59bd4c6c9124eeb3a853095601cf0/app/assets/images/Logo.svg" %>
      <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Courses", courses_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Free resources", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Blog", posts_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn-login", id: "login" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1>Hi </h1>

<% if @user.photo.attached? %>
  <% cl_image_tag @user.photo.key, class: "avatar" %>
<% else %>
  <% image_tag "https://avatars2.githubusercontent.com/u/68373422?s=400&u=c0305c43aae7809c60f21317727ed80471260fe0&v=4", class: "avatar dropdown-toggle" %>
<% end %>
<div class="container">
  <%= link_to "Add a deck", new_user_deck_path(@user), class: "btn btn-dark" %>
</div>

<%= link_to "Edit Profile", edit_user_registration_path(current_user)%>